### PR TITLE
[TestFix] Update gluster and heketi volume mapping TC tier

### PR DESCRIPTION
**Pull request by vamahaja**
Update TC `test_arbiter_scaled_heketi_and_gluster_volume_mapping` marker from `tier4` to `tier3`

### CODE REVIEW

**Review by srivickynesh — COMMENTED** [review]
Scaled Tc's are present in tier4. why to move this to tier 3?

**Comment by vamahaja** [comment]
@srivickynesh this TC is not executed on scaled setup. It will create nearly 100 volumes and test heketi and gluster volume mapping.

**Review by srivickynesh — APPROVED** [review]

**Review by aloganat — APPROVED** [review]
LGTM

**Review by adityaramteke — CHANGES_REQUESTED** [review]
Remove tests/gct-non-functional

**Review by adityaramteke — APPROVED** [review]
LGTM

**Review by srivickynesh — APPROVED** [review]

**Pull request merged**
