### PR TITLE
[Lib] Add support to create PVC with label

### PR DESCRIPTION
**Pull request by SushilG96**
Added support for creating PVC with label

### CODE REVIEW

**Comment by srivickynesh** [comment]
The Main goal is here to add labels support in libs. Please address these changes in a single PR.

**Comment by SushilG96** [comment]
@srivickynesh Yes, the goal is the same, but it has to be indifferent operations.
1. For creating PVC with the label.
2. For deleting PVC with the label.

**Comment by srivickynesh** [comment]
Please rebase the patch

**Review by srivickynesh — COMMENTED** [review]
Are these two library create with label and delete with label falls under same testcase?

**Review by vamahaja — CHANGES_REQUESTED** [review]
Remove changes related to baseclass.py as there is separate PR raised - https://github.com/gluster/glusterfs-containers-tests/pull/29

**Review by vamahaja — APPROVED** [review]

**Review by adityaramteke — APPROVED** [review]
LGTM

**Pull request merged**
